// This file was autogenerated by ./bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('Circle.js', ['Circle'], ['Figure']);
goog.addDependency('Figure.js', ['Figure'], []);
goog.addDependency('base.js', ['goog'], []);
